version: "3.9"
services:
  app-service:
    image: andreinanu/app-service
    restart: "always"
    environment:
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP:-localhost}
    ports:
      - "8000:8000"
    depends_on:
      auth-service:
        condition: service_started
  auth-service:
    image: andreinanu/auth-service
    restart: "always"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  
  # Uncomment for local deployments    

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@email.com}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db
  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"
volumes:
  db:
    driver: local